// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuQlZGvCSwcHnOGSeBvnLlF08ZBodBQgk',
    appId: '1:1022602872125:web:f58db38f45e9730fc33154',
    messagingSenderId: '1022602872125',
    projectId: 'empolyee-db',
    authDomain: 'empolyee-db.firebaseapp.com',
    databaseURL: 'https://empolyee-db-default-rtdb.firebaseio.com',
    storageBucket: 'empolyee-db.firebasestorage.app',
    measurementId: 'G-27WVEXHB62',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtg_sUNDsVSOiUgUyBK0ZNcFGCC6XbgVU',
    appId: '1:1022602872125:android:48f47c11c6b7b611c33154',
    messagingSenderId: '1022602872125',
    projectId: 'empolyee-db',
    databaseURL: 'https://empolyee-db-default-rtdb.firebaseio.com',
    storageBucket: 'empolyee-db.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuQlZGvCSwcHnOGSeBvnLlF08ZBodBQgk',
    appId: '1:1022602872125:web:840f2c2cae12d054c33154',
    messagingSenderId: '1022602872125',
    projectId: 'empolyee-db',
    authDomain: 'empolyee-db.firebaseapp.com',
    databaseURL: 'https://empolyee-db-default-rtdb.firebaseio.com',
    storageBucket: 'empolyee-db.firebasestorage.app',
    measurementId: 'G-M9NEGF6513',
  );

}